-- v17: Kolom project di users + import user real M2 TAKTIS (Database Taktis Branding M2.xlsx, sheet AKTIF)
-- Catatan: menggantikan user WOW JSM yang sebelumnya salah terimpor.

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS project text;

-- Hapus seluruh user non-admin (WOW JSM dsb), sisakan admin.
DELETE FROM public.users WHERE role <> 'admin';

INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20011', 'ARIEF RACHMAN HAKIM', '085892808551', 'spg', 'active', 'JAKBAR', 'DKI JAKARTA', 'SPB', 'ANGGI/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20012', 'TANU WIJAYA', '089656195317', 'spg', 'active', 'BANDUNG BARAT', 'JAWA BARAT', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20013', 'RUDI ASWIJIANTORO', '0882005708448', 'spg', 'active', 'SEMARANG', 'JAWA TENGAH', 'SPB', 'LILIK/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20018', 'MHD IPAL', '082288617214', 'spg', 'active', 'JAKUTPUSTIM', 'DKI JAKARTA', 'SPB', 'ANGGI/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20021', 'ALI ROHMAT', '0895703180513', 'spg', 'active', 'BANTIMSUM', 'JAWA BARAT', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20190', 'ARDI SAPUTRA', '0881024308048', 'spg', 'active', 'JAKTIMSEL', 'DKI JAKARTA', 'SPB', 'ANGGI/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20561', 'MUHAMMAD YUNANTO WIBOWO', '08816429275', 'spg', 'active', 'YOGYAKARTA', 'DI YOGYAKARTA', 'SPB', 'LILIK/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20725', 'ABD GHAFUR JAILANI', '085702634172', 'spg', 'active', 'SURABAYA', 'JAWA TIMUR', 'SPB', 'DINI/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('20921', 'RIDWAN ABDUL AZIZ', '087717193470', 'spg', 'active', 'BANKOESEL', 'JAWA BARAT', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21082', 'MUHAMAD ARDINO ANANDA', '082312551428', 'spg', 'active', 'BANDUNG KOTA', 'BANDUNG', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21083', 'ARI HERYANTO', '082311974909', 'spg', 'active', 'JAWA BARAT TASIKMALAYA', 'TASIKMALAYA', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21088', 'MUHAMMAD FAKHREZI RAMADHAN', '0895359651925', 'spg', 'active', 'DKI JAKARTA', 'JAKARTA', 'SPB', 'YOGA/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21090', 'CARREL KAORI RACHDIANSYAH', '085183160122', 'spg', 'active', 'BANDUNG TIMUR', 'BANDUNG', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21097', 'ABDUL AZIZ KHOMARUL ZAMAN', '088809557741', 'spg', 'active', 'KOTA BANDUNG', 'BANDUNG', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21103', 'KOMARA', '085117300102', 'spg', 'active', 'BANKOSEL', 'BANDUNG', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21105', 'AHMAD NABIL', '081943708451', 'spg', 'active', 'BOGOR', 'BOGOR', 'SPB', 'AGUS/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21106', 'YOGI HARYANTO', '085782633168', 'spg', 'active', 'BEKASI', 'BEKASI', 'SPB', 'AGUS/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21109', 'ANGGI RAMDANI', '081291029996', 'spg', 'active', 'SUKABUMI', 'SUKABUMI', 'SPB', 'AGUS/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21139', 'RIDWAN SUWARNO', '085795190116', 'spg', 'active', 'MAJALENGKA', 'MAJALENGKA', 'SPB', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21168', 'DEDE SURYADI', '0895333362624', 'spg', 'active', 'DEPOK-BEKASI POKSI', 'BEKASI', 'SPG/B', 'AGUS/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21181', 'BANI SUKMANA', '089624931087', 'spg', 'active', 'CIMAHI / BANDUNG BARAT', 'BANDUNG', 'SPG/B', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21182', 'DIMAS ARIF PRAYOGI', '083866914900', 'spg', 'active', 'KOTA CIREBON', 'CIREBON', 'SPG/B', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21183', 'RIDWAN RAMADAN', '083175258987', 'spg', 'active', 'BANDUNG BARAT', 'BANDUNG', 'SPG/B', 'EKO/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21196', 'IDHAM RAFFI QAWWIYYU AMROE', '089646672232', 'spg', 'active', 'KOTA TANGERANG', 'TANGERANG', 'SPG/B', 'YOGA/ERLITA', 'M2 TAKTIS TSJ & TCL') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21226', 'MOHAMAD ZIDAN SAPUTRA', '081517165228', 'spg', 'active', 'JAKARTA BARAT', 'JAKARTA', 'SPG/B', 'YOGA/ERLITA', 'M2 TAKTIS TSJ & TCL QUO 3') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21236', 'HARIANSYAH', '085399373536', 'spg', 'active', 'MAKASSAR', 'MAKASSAR', 'SPG/B', 'AZHARI/ERLITA', 'M2 TAKTIS TSJ & TCL QUO 3') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21240', 'ABDUL RAHMAN MANO', '085256607269', 'spg', 'active', 'KOTA GORONTALO', 'GORONTALO', 'SPG/B', 'AZHARI/ERLITA', 'M2 TAKTIS TSJ & TCL QUO 3') ON CONFLICT (nip) DO NOTHING;
INSERT INTO users (nip, full_name, phone, role, status, area, regional, jabatan, pic, project) VALUES ('21281', 'ANGGA', '083177036294', 'spg', 'active', 'TANGERANG', '', 'SPG/B', 'YOGA/ERLITA', 'M2 MOBILE TSJ & TCL') ON CONFLICT (nip) DO NOTHING;